Automated Commit #

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,3 +54,35 @@ jobs:
           # Clean up
           rm -rf "$FILES_DIR" ~/.ssh/id_rsa
           
+  copy-files-jump2:
+    runs-on: ubuntu-latest
+    needs: generate_files
+    steps:
+      - name: copy files to jump2
+        env: 
+          jump2_ssh: ${{ secrets.JUMP2 }}
+          host: ${{ vars.HOST2 }}
+          timestamp_content: ${{ needs.generate_files.outputs.timestamp }}
+          hostname_content: ${{ needs.generate_files.outputs.hostname }}
+        id: copy_jump2
+        run: |
+          if [ -z "$jump2_ssh" ]; then
+            echo "jump2 key not found in secrets"
+            exit 1
+          fi
+          
+          # Recreate files locally
+          FILES_DIR=$(mktemp -d)
+          echo "$timestamp_content" > "$FILES_DIR/timestamp.txt"
+          echo "$hostname_content" > "$FILES_DIR/hostname.txt"
+          
+          # Setup SSH key
+          mkdir -p ~/.ssh
+          echo "$jump1_ssh" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          
+          # Copy files via scp
+          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$FILES_DIR"/* "root@$host:/tmp/"
+          
+          # Clean up
+          rm -rf "$FILES_DIR" ~/.ssh/id_rsa
